name: CI

on: [push, workflow_dispatch] # allow manual call

jobs:
  build-and-test-linux:
    uses: ReactionMechanismGenerator/RMG-Py/.github/workflows/CI.yml@main
    with:
      rmg-db-branch: ${GITHUB_REF_NAME}
