name: CI

on: [push, workflow_dispatch] # allow manual call

jobs:
  get-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
  rmg-py-ci:
    needs: get-branch
    uses: ReactionMechanismGenerator/RMG-Py/.github/workflows/CI.yml@main
    with:
      rmg-db-branch: ${{ needs.get-branch.outputs.branch }}
