name: Conda Build

on:
  pull_request:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      # Step to create a custom condarc.yml before setting up conda
      - name: Create custom conda config file
        run: |
          RUNNER_CWD=$(pwd)
          echo "channels:" > $RUNNER_CWD/condarc.yml
          echo "  - conda-forge" >> $RUNNER_CWD/condarc.yml
          echo "show_channel_urls: true" >> $RUNNER_CWD/condarc.yml

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          use-mamba: true
          condarc-file: condarc.yml
          auto-update-conda: false
          auto-activate-base: true
          activate-environment: ""

      - name: Install Build Tools
        run: mamba install python anaconda-client conda-build conda-verify

      - name: Configure Auto-Upload
        if: github.ref == 'refs/heads/stable'
        run: |
          conda config --set anaconda_upload yes

      - name: Build Binary
        run: |
          # Set the CONDA_TOKEN environment variable
          if [ -z "${{ secrets.ANACONDA_TOKEN }}" ]; then
            export CONDA_TOKEN="default_value"
          else
            export CONDA_TOKEN="${{ secrets.ANACONDA_TOKEN }}"
          fi

          echo "CONDA_TOKEN=$CONDA_TOKEN" >> $GITHUB_ENV
      
          # Conditionally add the --token and --user flags for stable branches
          if [[ "${GITHUB_REF}" == "refs/heads/stable" ]]; then
            conda-build --token "$CONDA_TOKEN" --user rmg .conda
          else        
            conda-build .conda
          fi
